# Site settings
title:              Dimitrios Chamzas - Portfolio
email:              chamzas95@gmail.com
description:        "Dimitris Chamzas - Portfolio"
url:                "http://localhost:4000"
baseurl:            /DimitriosChamzas

github_username: jimas95
LinkedIn_username: Dimitris Chamzas
facebook_username: Dimitris Chamzas

# File structure settings
image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty